# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'button.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(950, 815)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(950, 450))
        MainWindow.setMaximumSize(QtCore.QSize(950, 850))
        MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 160))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setGeometry(QtCore.QRect(300, 20, 71, 33))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.login = QtWidgets.QLineEdit(self.groupBox_5)
        self.login.setGeometry(QtCore.QRect(390, 20, 181, 34))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.login.setFont(font)
        self.login.setText("")
        self.login.setPlaceholderText("")
        self.login.setObjectName("login")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(290, 70, 91, 33))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.password = QtWidgets.QLineEdit(self.groupBox_5)
        self.password.setGeometry(QtCore.QRect(390, 70, 181, 34))
        self.password.setText("")
        self.password.setFrame(True)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setPlaceholderText("")
        self.password.setObjectName("password")
        self.saveCred = QtWidgets.QPushButton(self.groupBox_5)
        self.saveCred.setGeometry(QtCore.QRect(420, 110, 121, 28))
        self.saveCred.setObjectName("saveCred")
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setEnabled(False)
        self.label_10.setGeometry(QtCore.QRect(750, 20, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setEnabled(False)
        self.label_13.setGeometry(QtCore.QRect(750, 40, 161, 16))
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 250))
        self.tabWidget.setObjectName("tabWidget")
        self.check_journals = QtWidgets.QWidget()
        self.check_journals.setEnabled(True)
        self.check_journals.setObjectName("check_journals")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.check_journals)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.check_journals)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(300, 85))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(120, 30, 82, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(87, 27))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.class1 = QtWidgets.QSpinBox(self.groupBox_4)
        self.class1.setGeometry(QtCore.QRect(220, 30, 80, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.class1.sizePolicy().hasHeightForWidth())
        self.class1.setSizePolicy(sizePolicy)
        self.class1.setMinimumSize(QtCore.QSize(80, 35))
        self.class1.setMinimum(1)
        self.class1.setMaximum(11)
        self.class1.setObjectName("class1")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(310, 30, 8, 33))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.class2 = QtWidgets.QSpinBox(self.groupBox_4)
        self.class2.setGeometry(QtCore.QRect(330, 30, 80, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.class2.sizePolicy().hasHeightForWidth())
        self.class2.setSizePolicy(sizePolicy)
        self.class2.setMinimumSize(QtCore.QSize(80, 35))
        self.class2.setMinimum(1)
        self.class2.setMaximum(11)
        self.class2.setObjectName("class2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(460, 30, 103, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.term1 = QtWidgets.QSpinBox(self.groupBox_4)
        self.term1.setGeometry(QtCore.QRect(580, 30, 80, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.term1.sizePolicy().hasHeightForWidth())
        self.term1.setSizePolicy(sizePolicy)
        self.term1.setMinimumSize(QtCore.QSize(80, 35))
        self.term1.setMinimum(1)
        self.term1.setMaximum(4)
        self.term1.setObjectName("term1")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(670, 30, 8, 33))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.term2 = QtWidgets.QSpinBox(self.groupBox_4)
        self.term2.setGeometry(QtCore.QRect(690, 30, 80, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.term2.sizePolicy().hasHeightForWidth())
        self.term2.setSizePolicy(sizePolicy)
        self.term2.setMinimumSize(QtCore.QSize(80, 35))
        self.term2.setMaximumSize(QtCore.QSize(80, 35))
        self.term2.setAcceptDrops(False)
        self.term2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.term2.setMinimum(1)
        self.term2.setMaximum(4)
        self.term2.setObjectName("term2")
        self.verticalLayout.addWidget(self.groupBox_4)
        self.scrollArea = QtWidgets.QScrollArea(self.check_journals)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 100))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 877, 1054))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout.setObjectName("formLayout")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_7)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.check_RO = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_RO.sizePolicy().hasHeightForWidth())
        self.check_RO.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.check_RO.setFont(font)
        self.check_RO.setAcceptDrops(False)
        self.check_RO.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.check_RO.setIconSize(QtCore.QSize(20, 20))
        self.check_RO.setTristate(False)
        self.check_RO.setObjectName("check_RO")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.check_RO)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.check_meta = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.check_meta.setFont(font)
        self.check_meta.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.check_meta.setObjectName("check_meta")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.check_meta)
        spacerItem2 = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.check_lessons_fill = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_lessons_fill.sizePolicy().hasHeightForWidth())
        self.check_lessons_fill.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.check_lessons_fill.setFont(font)
        self.check_lessons_fill.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.check_lessons_fill.setObjectName("check_lessons_fill")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.check_lessons_fill)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(500, 170))
        self.groupBox.setObjectName("groupBox")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(20, 30, 709, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.lesson_percent = QtWidgets.QSpinBox(self.groupBox)
        self.lesson_percent.setEnabled(False)
        self.lesson_percent.setGeometry(QtCore.QRect(750, 30, 100, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lesson_percent.sizePolicy().hasHeightForWidth())
        self.lesson_percent.setSizePolicy(sizePolicy)
        self.lesson_percent.setMinimumSize(QtCore.QSize(70, 30))
        self.lesson_percent.setMaximumSize(QtCore.QSize(100, 60))
        self.lesson_percent.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lesson_percent.setWrapping(False)
        self.lesson_percent.setSpecialValueText("")
        self.lesson_percent.setPrefix("")
        self.lesson_percent.setMinimum(1)
        self.lesson_percent.setMaximum(100)
        self.lesson_percent.setProperty("value", 25)
        self.lesson_percent.setObjectName("lesson_percent")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(20, 70, 461, 28))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.allowed_not_row = QtWidgets.QLineEdit(self.groupBox)
        self.allowed_not_row.setEnabled(False)
        self.allowed_not_row.setGeometry(QtCore.QRect(20, 110, 500, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allowed_not_row.sizePolicy().hasHeightForWidth())
        self.allowed_not_row.setSizePolicy(sizePolicy)
        self.allowed_not_row.setMinimumSize(QtCore.QSize(500, 30))
        self.allowed_not_row.setMaximumSize(QtCore.QSize(500, 30))
        self.allowed_not_row.setInputMask("")
        self.allowed_not_row.setText("")
        self.allowed_not_row.setFrame(True)
        self.allowed_not_row.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.allowed_not_row.setObjectName("allowed_not_row")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.groupBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(10, QtWidgets.QFormLayout.LabelRole, spacerItem3)
        self.check_students_fill = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.check_students_fill.setFont(font)
        self.check_students_fill.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.check_students_fill.setObjectName("check_students_fill")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.check_students_fill)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(500, 110))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(20, 40, 703, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.term_percent = QtWidgets.QSpinBox(self.groupBox_2)
        self.term_percent.setEnabled(False)
        self.term_percent.setGeometry(QtCore.QRect(740, 40, 100, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.term_percent.sizePolicy().hasHeightForWidth())
        self.term_percent.setSizePolicy(sizePolicy)
        self.term_percent.setMinimumSize(QtCore.QSize(70, 30))
        self.term_percent.setMaximumSize(QtCore.QSize(100, 60))
        self.term_percent.setMinimum(1)
        self.term_percent.setMaximum(100)
        self.term_percent.setProperty("value", 30)
        self.term_percent.setObjectName("term_percent")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.SpanningRole, self.groupBox_2)
        spacerItem4 = QtWidgets.QSpacerItem(0, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(13, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        self.check_double_two = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.check_double_two.setFont(font)
        self.check_double_two.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.check_double_two.setObjectName("check_double_two")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.check_double_two)
        spacerItem5 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(15, QtWidgets.QFormLayout.LabelRole, spacerItem5)
        self.check_term_marks = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.check_term_marks.setFont(font)
        self.check_term_marks.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.check_term_marks.setObjectName("check_term_marks")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.check_term_marks)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(500, 212))
        self.groupBox_3.setObjectName("groupBox_3")
        self.min_for_3 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.min_for_3.setEnabled(False)
        self.min_for_3.setGeometry(QtCore.QRect(430, 150, 100, 30))
        self.min_for_3.setMinimumSize(QtCore.QSize(70, 30))
        self.min_for_3.setMaximumSize(QtCore.QSize(100, 60))
        self.min_for_3.setDecimals(1)
        self.min_for_3.setMinimum(2.0)
        self.min_for_3.setMaximum(3.0)
        self.min_for_3.setSingleStep(0.1)
        self.min_for_3.setProperty("value", 2.5)
        self.min_for_3.setObjectName("min_for_3")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(21, 32, 370, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.min_for_4 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.min_for_4.setEnabled(False)
        self.min_for_4.setGeometry(QtCore.QRect(430, 90, 100, 30))
        self.min_for_4.setMinimumSize(QtCore.QSize(70, 30))
        self.min_for_4.setMaximumSize(QtCore.QSize(100, 60))
        self.min_for_4.setDecimals(1)
        self.min_for_4.setMinimum(3.0)
        self.min_for_4.setMaximum(4.0)
        self.min_for_4.setSingleStep(0.1)
        self.min_for_4.setProperty("value", 3.5)
        self.min_for_4.setObjectName("min_for_4")
        self.min_for_5 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.min_for_5.setEnabled(False)
        self.min_for_5.setGeometry(QtCore.QRect(430, 30, 100, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_for_5.sizePolicy().hasHeightForWidth())
        self.min_for_5.setSizePolicy(sizePolicy)
        self.min_for_5.setMinimumSize(QtCore.QSize(70, 30))
        self.min_for_5.setMaximumSize(QtCore.QSize(100, 60))
        self.min_for_5.setDecimals(1)
        self.min_for_5.setMinimum(4.0)
        self.min_for_5.setMaximum(5.0)
        self.min_for_5.setSingleStep(0.1)
        self.min_for_5.setProperty("value", 4.5)
        self.min_for_5.setObjectName("min_for_5")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(21, 90, 370, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(21, 150, 370, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.SpanningRole, self.groupBox_3)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.group_by = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_by.sizePolicy().hasHeightForWidth())
        self.group_by.setSizePolicy(sizePolicy)
        self.group_by.setMinimumSize(QtCore.QSize(171, 30))
        self.group_by.setEditable(False)
        self.group_by.setCurrentText("")
        self.group_by.setMaxVisibleItems(5)
        self.group_by.setMaxCount(3)
        self.group_by.setObjectName("group_by")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.LabelRole, self.group_by)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.groupBox_6 = QtWidgets.QGroupBox(self.check_journals)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 94))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_6)
        self.progressBar.setGeometry(QtCore.QRect(580, 40, 230, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(230, 0))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.start_check = QtWidgets.QPushButton(self.groupBox_6)
        self.start_check.setGeometry(QtCore.QRect(360, 20, 211, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_check.sizePolicy().hasHeightForWidth())
        self.start_check.setSizePolicy(sizePolicy)
        self.start_check.setMinimumSize(QtCore.QSize(211, 50))
        self.start_check.setCheckable(False)
        self.start_check.setObjectName("start_check")
        self.pb_label = QtWidgets.QLabel(self.groupBox_6)
        self.pb_label.setGeometry(QtCore.QRect(580, 20, 311, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_label.sizePolicy().hasHeightForWidth())
        self.pb_label.setSizePolicy(sizePolicy)
        self.pb_label.setMinimumSize(QtCore.QSize(230, 15))
        self.pb_label.setObjectName("pb_label")
        self.verticalLayout.addWidget(self.groupBox_6)
        self.tabWidget.addTab(self.check_journals, "")
        self.report = QtWidgets.QWidget()
        self.report.setObjectName("report")
        self.rep_term = QtWidgets.QSpinBox(self.report)
        self.rep_term.setGeometry(QtCore.QRect(450, 30, 71, 31))
        self.rep_term.setMinimum(1)
        self.rep_term.setMaximum(4)
        self.rep_term.setObjectName("rep_term")
        self.label_8 = QtWidgets.QLabel(self.report)
        self.label_8.setGeometry(QtCore.QRect(320, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.start_grade = QtWidgets.QSpinBox(self.report)
        self.start_grade.setGeometry(QtCore.QRect(450, 90, 71, 31))
        self.start_grade.setMinimum(1)
        self.start_grade.setMaximum(11)
        self.start_grade.setObjectName("start_grade")
        self.label_9 = QtWidgets.QLabel(self.report)
        self.label_9.setGeometry(QtCore.QRect(250, 90, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.rep_progressBar = QtWidgets.QProgressBar(self.report)
        self.rep_progressBar.setGeometry(QtCore.QRect(360, 280, 251, 21))
        self.rep_progressBar.setProperty("value", 0)
        self.rep_progressBar.setTextVisible(True)
        self.rep_progressBar.setInvertedAppearance(False)
        self.rep_progressBar.setObjectName("rep_progressBar")
        self.create_report = QtWidgets.QPushButton(self.report)
        self.create_report.setGeometry(QtCore.QRect(360, 170, 211, 51))
        self.create_report.setCheckable(False)
        self.create_report.setObjectName("create_report")
        self.rep_pb_label = QtWidgets.QLabel(self.report)
        self.rep_pb_label.setGeometry(QtCore.QRect(360, 250, 321, 20))
        self.rep_pb_label.setObjectName("rep_pb_label")
        self.tabWidget.addTab(self.report, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.group_by.setCurrentIndex(-1)
        self.check_lessons_fill.toggled['bool'].connect(self.groupBox.setEnabled)
        self.check_students_fill.toggled['bool'].connect(self.groupBox_2.setEnabled)
        self.check_term_marks.toggled['bool'].connect(self.groupBox_3.setEnabled)
        self.check_lessons_fill.toggled['bool'].connect(self.lesson_percent.setEnabled)
        self.check_lessons_fill.toggled['bool'].connect(self.allowed_not_row.setEnabled)
        self.check_students_fill.toggled['bool'].connect(self.term_percent.setEnabled)
        self.check_term_marks.toggled['bool'].connect(self.min_for_5.setEnabled)
        self.check_term_marks.toggled['bool'].connect(self.min_for_4.setEnabled)
        self.check_term_marks.toggled['bool'].connect(self.min_for_3.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EduTatar"))
        self.label.setText(_translate("MainWindow", "Логин"))
        self.label_2.setText(_translate("MainWindow", "Пароль"))
        self.saveCred.setText(_translate("MainWindow", "Запомнить"))
        self.label_10.setText(_translate("MainWindow", "Dev: Ruslan Khayrutdinov"))
        self.label_13.setText(_translate("MainWindow", "onsunday1703@gmail.com"))
        self.label_5.setText(_translate("MainWindow", "Классы"))
        self.label_6.setText(_translate("MainWindow", "-"))
        self.label_3.setText(_translate("MainWindow", "Четверти"))
        self.label_4.setText(_translate("MainWindow", "-"))
        self.label_7.setText(_translate("MainWindow", "Параметры проверки"))
        self.check_RO.setText(_translate("MainWindow", "После Контрольной Работы должна быть Работа над Ошибками"))
        self.check_meta.setText(_translate("MainWindow", "Заполнены ли темы уроков и ДЗ"))
        self.check_lessons_fill.setText(_translate("MainWindow", "Количество выставленных за урок оценок"))
        self.groupBox.setTitle(_translate("MainWindow", "Доп. параметры"))
        self.label_11.setText(_translate("MainWindow", "Минимальный процент выставленных за урок оценок (не включая Н и Б)"))
        self.lesson_percent.setSuffix(_translate("MainWindow", "%"))
        self.lesson_percent.setProperty("label", _translate("MainWindow", "ssg"))
        self.label_12.setText(_translate("MainWindow", "Предметы, где \"ПР\" не требует колонки оценок"))
        self.allowed_not_row.setPlaceholderText(_translate("MainWindow", "напр: Алгебра, Геометрия, Математика"))
        self.check_students_fill.setText(_translate("MainWindow", "Количество оценок у ученика за четверть"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Доп. параметры"))
        self.label_14.setText(_translate("MainWindow", "Минимальный процент оценок у ученика за четверть (не включая Н и Б)"))
        self.term_percent.setSuffix(_translate("MainWindow", "%"))
        self.check_double_two.setText(_translate("MainWindow", "Не поставлено ли у ученика две двойки подряд"))
        self.check_term_marks.setText(_translate("MainWindow", "Четвертные оценки"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Доп. параметры"))
        self.label_17.setText(_translate("MainWindow", "Минимальный балл для четвертной 5"))
        self.label_18.setText(_translate("MainWindow", "Минимальный балл для четвертной 4"))
        self.label_19.setText(_translate("MainWindow", "Минимальный балл для четвертной 3"))
        self.label_20.setText(_translate("MainWindow", "Как отсортировать таблицы?"))
        self.start_check.setText(_translate("MainWindow", "Проверить"))
        self.pb_label.setText(_translate("MainWindow", "Инфо"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.check_journals), _translate("MainWindow", "Проверить журналы"))
        self.label_8.setText(_translate("MainWindow", "Четверть"))
        self.label_9.setText(_translate("MainWindow", "С какого класса"))
        self.create_report.setText(_translate("MainWindow", "Создать отчет"))
        self.rep_pb_label.setText(_translate("MainWindow", "Инфо"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.report), _translate("MainWindow", "Отчет за четверть"))
